# 🧩 Creating Arrays in NumPy

## 🎯 Learning Objectives

- Create NumPy arrays.
- Learn different array creation methods.
- Understand the `dtype` parameter.
- Create 1D, 2D, and 3D arrays.
- Generate special arrays.

## 📖 Introduction

NumPy provides multiple ways to create arrays for different use cases. Arrays are the core data structure in NumPy and are the foundation for numerical computing and machine learning.

## 📦 Creating Arrays from Python Lists

Convert a Python list into a NumPy array using `np.array()`.

In [1]:
import numpy as np 
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


## 📊 Creating a 2D Array

A 2D array represents rows and columns, similar to a matrix.

In [2]:
import numpy as np
arr = np.array([[10,20,30],
               [40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


## 🧊 Creating a 3D Array

A 3D array consists of multiple 2D arrays stacked together.

In [3]:
import numpy as np
arr = np.array([
    [[1,2], [3,4],[5,6]]])
print(arr)

[[[1 2]
  [3 4]
  [5 6]]]


## 🔢 Specifying Data Type (`dtype`)

Use the `dtype` parameter to define the type of elements stored in the array.

In [4]:
arr = np.array([1,2,3], dtype=float)
print(arr)

[1. 2. 3.]


## 0️⃣ np.zeros()

Creates an array filled with zeros.

In [5]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## 1️⃣ np.ones()

Creates an array filled with ones.

In [6]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


## 📄 np.empty()

Creates an array without initializing values.

In [7]:
arr = np.empty((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


## 🆔 np.eye()

Creates an identity matrix.

In [9]:
arr = np.eye(2)
print(arr)

[[1. 0.]
 [0. 1.]]


## 🔢 np.arange()

Creates evenly spaced values within a given range.

In [11]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


## 📏 np.linspace()

Creates evenly spaced numbers between two limits.

In [12]:
arr = np.linspace(0,1,5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


## 🎲 Random Arrays

Generate random numbers using NumPy.

In [13]:
arr = np.random.rand(3,3)
print(arr)

[[0.90860103 0.29662946 0.11775798]
 [0.11834951 0.4750468  0.90681329]
 [0.60687455 0.71323793 0.21310654]]


In [17]:
arr = np.random.randint(1,100, (3,3))
print(arr)

[[29 50 86]
 [26 73 93]
 [78 82 11]]


## 📝 Summary

- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.empty()`
- `np.eye()`
- `np.arange()`
- `np.linspace()`
- `np.random.rand()`
- `np.random.randint()`