# 📊 NumPy Array Attributes

## 🎯 Learning Objectives

- Understand NumPy array attributes.
- Learn how to inspect an array.
- Differentiate between shape, size, and dimension.
- Understand memory usage of arrays.
- Convert array data types.

## 📖 Introduction

Every NumPy array contains metadata that describes its structure, size, data type, and memory usage. These properties are known as **Array Attributes**. Understanding these attributes is essential for data manipulation, debugging, and optimizing machine learning workflows.

In [1]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr)

[[10 20 30]
 [40 50 60]]


## 🔹 `ndim`

Returns the **number of dimensions (axes)** of the array.

- 1D → One axis
- 2D → Two axes
- 3D → Three axes

In [2]:
print(arr.ndim)

2


## 🔹 `shape`

Returns the shape of the array as **(rows, columns)**.

Syntax:

```python
array.shape
```

In [3]:
print(arr.shape)

(2, 3)


## 🔹 `size`

Returns the **total number of elements** in the array.

In [4]:
print(arr.size)

6


## 🔹 `dtype`

Returns the **data type** of array elements.

In [5]:
print(arr.dtype)

int64


## 🔹 `itemsize`

Returns the size of **one array element** in bytes.

In [6]:
print(arr.itemsize)

8


## 🔹 `nbytes`

Returns the **total memory occupied** by the array.

Formula:

Total Memory = size × itemsize

In [7]:
print(arr.nbytes)

48


## 🔹 `T`

Returns the transpose of an array by interchanging rows and columns.

In [8]:
print(arr.T)

[[10 40]
 [20 50]
 [30 60]]


## 🔹 `astype()`

Converts the array from one data type to another.

In [9]:
new_arr = arr.astype(float)
print(new_arr)
print(new_arr.dtype)

[[10. 20. 30.]
 [40. 50. 60.]]
float64


## 📝 Summary

- `ndim` → Number of dimensions
- `shape` → Rows and columns
- `size` → Total elements
- `dtype` → Element data type
- `itemsize` → Bytes per element
- `nbytes` → Total memory used
- `T` → Transpose the array
- `astype()` → Convert data type