## 🎯 Learning Objectives

- Access array elements using indexing.
- Extract subsets of arrays using slicing.
- Understand positive and negative indexing.
- Perform indexing on 1D, 2D, and 3D arrays.
- Learn Fancy Indexing and Boolean Indexing.

## 📖 Introduction

Indexing and Slicing are essential techniques for accessing and manipulating data in NumPy arrays. These operations allow you to retrieve individual elements, rows, columns, or subsets of data efficiently without modifying the original array.

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

## 🔹 1D Array Indexing

Access elements using their index position.

**Syntax**

```python
array[index]
```

In [2]:
print(arr1[0])
print(arr1[2])
print(arr1[4])

10
30
50


## 🔹 Negative Indexing

Negative indices access elements from the end of the array.

- `-1` → Last element
- `-2` → Second last element

In [3]:
print(arr1[-1])
print(arr1[-2])

50
40


## 🔹 1D Array Slicing

Extract a portion of an array.

**Syntax**

```python
array[start:stop:step]
```

In [4]:
print(arr1[1:4])
print(arr1[:3])
print(arr1[2:])
print(arr1[::2])

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


## 🔹 2D Array Indexing

Use row and column indices to access elements.

**Syntax**

```python
array[row, column]
```

In [5]:
print(arr2[0, 1])
print(arr2[2, 2])
print(arr2[1, 0])

2
9
4


## 🔹 Accessing Rows

Select an entire row using the row index.

In [6]:
print(arr2[0])
print(arr2[2])

[1 2 3]
[7 8 9]


## 🔹 Accessing Columns

Select an entire column using `:`.

In [7]:
print(arr2[:, 0])
print(arr2[:, 2])

[1 4 7]
[3 6 9]


## 🔹 2D Array Slicing

Extract specific rows and columns.

**Syntax**

```python
array[row_start:row_end, col_start:col_end]
```

In [8]:
print(arr2[0:2, 1:3])

[[2 3]
 [5 6]]


## 🔹 3D Array Indexing

Use three indices to access elements.

**Syntax**

```python
array[depth, row, column]
```

In [9]:
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr3[1, 0, 1])

6


## 🔹 Fancy Indexing

Access multiple elements using a list of indices.

In [10]:
print(arr1[[0, 2, 4]])

[10 30 50]


## 🔹 Boolean Indexing

Filter elements based on a condition.

In [ ]:
print(arr1[arr1 > 25])

## 📝 Summary

- Indexing accesses individual elements.
- Slicing extracts subsets of data.
- Negative indexing starts from the end.
- 2D arrays use row and column indices.
- Fancy indexing selects multiple elements.
- Boolean indexing filters data based on conditions.