# 🔄 NumPy Array Reshaping

## 🎯 Learning Objectives

- Understand array reshaping.
- Change array dimensions using `reshape()`.
- Flatten multidimensional arrays.
- Learn the difference between `flatten()` and `ravel()`.
- Resize arrays.
- Add and remove dimensions.

## 📖 Introduction

Array reshaping changes the structure of a NumPy array without changing its data. It is commonly used in Data Science and Machine Learning to prepare data before training models.

In [1]:
import numpy as np 
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 🔹 `reshape()`

Changes the shape of an array without changing its data.

**Syntax**

```python
array.reshape(rows, columns)
```

In [2]:
arr = np.arange(1, 13)
new_arr = arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 🔹 Reshape to 3D Array

Convert a 1D array into a 3D array.

In [3]:
arr = np.arange(1, 13)

new_arr = arr.reshape(2, 2, 3)

print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 🔹 Automatic Dimension (`-1`)

NumPy automatically calculates one dimension.

In [4]:
arr = np.arange(12)

print(arr.reshape(3, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 🔹 `flatten()`

Converts a multi-dimensional array into a 1D array.

Returns a **copy** of the original array.

In [5]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.flatten())

[1 2 3 4 5 6]


## 🔹 `ravel()`

Converts a multi-dimensional array into a 1D array.

Returns a **view** whenever possible.

In [6]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.ravel())

[1 2 3 4 5 6]


| `flatten()`  | `ravel()`                  |
| ------------ | -------------------------- |
| Returns Copy | Returns View (if possible) |
| More Memory  | Less Memory                |
| Slower       | Faster                     |


## 🔹 `resize()`

Changes the shape of an array **in-place**.

In [7]:
arr = np.array([1,2,3,4,5,6])

arr.resize((2,3))

print(arr)

[[1 2 3]
 [4 5 6]]


## 🔹 `transpose()`

Swaps rows and columns of an array.

In [8]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


## 🔹 `expand_dims()`

Adds a new axis (dimension) to an array.

In [9]:
arr = np.array([1,2,3])

print(np.expand_dims(arr, axis=0))

[[1 2 3]]


## 🔹 `squeeze()`

Removes dimensions of size 1.

In [10]:
arr = np.array([[[10,20,30]]])

print(np.squeeze(arr))

[10 20 30]


| Method          | Purpose              |
| --------------- | -------------------- |
| `reshape()`     | Change array shape   |
| `reshape(-1)`   | Automatic dimension  |
| `flatten()`     | Convert to 1D (Copy) |
| `ravel()`       | Convert to 1D (View) |
| `resize()`      | Resize array         |
| `transpose()`   | Swap rows & columns  |
| `expand_dims()` | Add dimension        |
| `squeeze()`     | Remove dimension     |


## 📝 Summary

- `reshape()` changes array dimensions.
- `flatten()` returns a copy.
- `ravel()` returns a view whenever possible.
- `resize()` modifies the original array.
- `transpose()` swaps rows and columns.
- `expand_dims()` adds a new axis.
- `squeeze()` removes unnecessary dimensions.