# ➕ NumPy Array Operations

## 📖 Introduction

NumPy allows mathematical operations to be performed directly on arrays without using loops. These operations are fast, efficient, and are the foundation of Data Science and Machine Learning.

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1)
print(arr2)

[10 20 30 40]
[1 2 3 4]


## ➕ Addition (`+`)

In [2]:
print(arr1 + arr2)

[11 22 33 44]


## ➖ Subtraction (`-`)

In [ ]:
print(arr1 - arr2)

## ✖️ Multiplication (`*`)

In [3]:
print(arr1 * arr2)

[ 10  40  90 160]


## ➗ Division (`/`)

In [4]:
print(arr1 / arr2)

[10. 10. 10. 10.]


## 🔢 Floor Division (`//`)

In [5]:
print(arr1 // arr2)

[10 10 10 10]


## 📌 Modulus (`%`)

In [7]:
print(arr1 % arr2)

[0 0 0 0]


## ⚡ Power (`**`)

In [8]:
print(arr2 ** 2)

[ 1  4  9 16]


## 🔹 Element-wise Operations

NumPy performs operations element by element.

In [9]:
print(arr1 + arr2)
print(arr1 * arr2)

[11 22 33 44]
[ 10  40  90 160]


## 🔹 Scalar Operations

Apply operations between an array and a single value.

In [10]:
print(arr1 + 10)
print(arr1 * 2)
print(arr1 / 5)

[20 30 40 50]
[20 40 60 80]
[2. 4. 6. 8.]


## ⚖️ Comparison Operators

In [11]:
print(arr1 > 20)
print(arr1 < 20)
print(arr1 == 20)
print(arr1 != 20)
print(arr1 >= 20)
print(arr1 <= 20)

[False False  True  True]
[ True False False False]
[False  True False False]
[ True False  True  True]
[False  True  True  True]
[ True  True False False]


## 📊 Aggregate Functions

In [12]:
print(np.sum(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.mean(arr1))
print(np.prod(arr2))

100
10
40
25.0
24


## 🧮 Mathematical Functions

In [13]:
print(np.sqrt(arr1))
print(np.square(arr2))
print(np.abs([-10, 20, -30]))
print(np.round([2.35, 3.75]))

[3.16227766 4.47213595 5.47722558 6.32455532]
[ 1  4  9 16]
[10 20 30]
[2. 4.]


| Operation      | Example        |
| -------------- | -------------- |
| Addition       | `arr1 + arr2`  |
| Subtraction    | `arr1 - arr2`  |
| Multiplication | `arr1 * arr2`  |
| Division       | `arr1 / arr2`  |
| Floor Division | `arr1 // arr2` |
| Modulus        | `arr1 % arr2`  |
| Power          | `arr ** 2`     |
| Sum            | `np.sum()`     |
| Mean           | `np.mean()`    |
| Max            | `np.max()`     |
| Min            | `np.min()`     |
| Product        | `np.prod()`    |
| Square Root    | `np.sqrt()`    |


## 📝 Summary

- NumPy performs element-wise operations.
- Supports arithmetic, comparison, and scalar operations.
- Aggregate functions summarize array values.
- Mathematical functions simplify numerical computations.
- Operations are faster than Python loops.