# 📡 NumPy Broadcasting

## 🎯 Learning Objectives

- Understand Broadcasting in NumPy.
- Learn the broadcasting rules.
- Perform operations on arrays of different shapes.
- Identify compatible and incompatible shapes.
- Apply broadcasting in real-world scenarios.

## 📖 Introduction

Broadcasting is a powerful NumPy feature that allows arithmetic operations on arrays with different shapes without explicitly copying data. It automatically expands the smaller array to match the larger array, making computations efficient and memory-friendly.

## 🔹 What is Broadcasting?

Broadcasting is the process by which NumPy automatically matches the shapes of arrays during arithmetic operations.

Instead of creating duplicate data, NumPy logically stretches the smaller array to perform element-wise operations.

## ❓ Why Broadcasting?

- Eliminates unnecessary loops.
- Improves performance.
- Saves memory.
- Simplifies array operations.
- Makes mathematical expressions concise.

## 📏 Broadcasting Rules

Two arrays are compatible if:

1. Their dimensions are equal.
2. One of the dimensions is **1**.
3. Missing dimensions are treated as **1**.

In [1]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr + 5)

[15 25 35]


In [2]:
a = np.array([1, 2, 3])

b = np.array([10, 20, 30])

print(a + b)

[11 22 33]


In [3]:
a = np.array([[1],
              [2],
              [3]])

b = np.array([10, 20, 30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [4]:
arr = np.array([[1],
                [2],
                [3]])

print(arr * 10)

[[10]
 [20]
 [30]]


## ❌ Incompatible Shapes

If the array shapes do not satisfy broadcasting rules, NumPy raises a `ValueError`.

In [6]:
a = np.array([1, 2, 3])

b = np.array([1, 2])

print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

ValueError: operands could not be broadcast together

## 🌍 Applications

- Image Processing
- Feature Scaling
- Data Normalization
- Neural Networks
- Matrix Computations
- Scientific Computing

## ✅ Advantages

- Faster computations
- Memory efficient
- Cleaner code
- Eliminates loops
- Optimized performance

| Operation            | Example                       |
| -------------------- | ----------------------------- |
| Scalar Broadcasting  | `arr + 5`                     |
| Array Broadcasting   | `a + b`                       |
| Matrix Broadcasting  | `matrix + vector`             |
| Invalid Broadcasting | Different incompatible shapes |


## 📝 Summary

- Broadcasting allows operations on arrays of different shapes.
- NumPy automatically expands compatible arrays.
- Broadcasting improves speed and memory efficiency.
- Incompatible shapes raise a `ValueError`.