# ⚡ NumPy Universal Functions (ufuncs)

## 🎯 Learning Objectives

- Understand Universal Functions (ufuncs).
- Learn unary and binary ufuncs.
- Perform mathematical operations efficiently.
- Use trigonometric, exponential, and logarithmic functions.
- Apply rounding functions.

In [1]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25])

## 🔹 Unary Functions

Unary ufuncs operate on a single array.

In [2]:
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [3]:
print(np.square(arr))

[  1  16  81 256 625]


In [4]:
arr = np.array([-10, -20, 30])

print(np.abs(arr))

[10 20 30]


In [5]:
arr = np.array([1, 2, 3])

print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


## 🔹 Logarithmic Functions

In [6]:
arr = np.array([1, 10, 100])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

[0.         2.30258509 4.60517019]
[0. 1. 2.]
[0.         3.32192809 6.64385619]


## 🔹 Trigonometric Functions

In [7]:
angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## 🔹 Rounding Functions

In [8]:
arr = np.array([2.3, 4.8, 5.5])

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[2. 5. 6.]
[2. 4. 5.]
[3. 5. 6.]


## 🔹 Binary Functions

Binary ufuncs operate on two arrays.

In [9]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [10]:
print(np.maximum(a,b))
print(np.minimum(a,b))

[10 20 30]
[1 2 3]


| Function        | Purpose        |
| --------------- | -------------- |
| `np.sqrt()`     | Square Root    |
| `np.square()`   | Square         |
| `np.abs()`      | Absolute Value |
| `np.exp()`      | Exponential    |
| `np.log()`      | Natural Log    |
| `np.log10()`    | Base-10 Log    |
| `np.sin()`      | Sine           |
| `np.cos()`      | Cosine         |
| `np.tan()`      | Tangent        |
| `np.round()`    | Round          |
| `np.floor()`    | Floor          |
| `np.ceil()`     | Ceiling        |
| `np.add()`      | Addition       |
| `np.subtract()` | Subtraction    |
| `np.multiply()` | Multiplication |
| `np.divide()`   | Division       |
| `np.maximum()`  | Maximum        |
| `np.minimum()`  | Minimum        |


## 📝 Summary

- Ufuncs perform fast element-wise operations.
- Unary ufuncs operate on one array.
- Binary ufuncs operate on two arrays.
- NumPy provides mathematical, logarithmic, trigonometric, and rounding functions.
- Ufuncs are optimized for high-performance numerical computing.