# 🧮 NumPy Linear Algebra

## 🎯 Learning Objectives

- Understand vectors and matrices.
- Perform matrix operations.
- Learn matrix multiplication techniques.
- Compute determinant, inverse, rank, and trace.
- Calculate eigenvalues and eigenvectors.
- Solve systems of linear equations.

## 📖 Introduction

Linear Algebra is the mathematical foundation of Machine Learning. NumPy provides the `numpy.linalg` module, which offers efficient functions for matrix computations used in algorithms like Linear Regression, PCA, SVM, and Neural Networks.

In [2]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

## ➕ Matrix Addition

In [3]:
print(A + B)

[[ 6  8]
 [10 12]]


## ➖ Matrix Subtraction

In [5]:
print(A - B)

[[-4 -4]
 [-4 -4]]


## ✖️ Matrix Multiplication

In [6]:
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [7]:
print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [8]:
print(A @ B)

[[19 22]
 [43 50]]


## 🔄 Transpose

In [9]:
print(A.T)

[[1 3]
 [2 4]]


## 📐 Determinant

In [10]:
print(np.linalg.det(A))

-2.0000000000000004


## 🔁 Inverse

In [11]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## 📊 Rank

In [12]:
print(np.linalg.matrix_rank(A))

2


## 📈 Trace

In [13]:
print(np.trace(A))

5


## 🧩 Eigenvalues & Eigenvectors

In [14]:
values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 📝 Solving Linear Equations

In [15]:
A = np.array([[2, 1],
              [1, 3]])

B = np.array([8, 13])

X = np.linalg.solve(A, B)

print(X)

[2.2 3.6]


| Function                  | Purpose                    |
| ------------------------- | -------------------------- |
| `np.dot()`                | Matrix multiplication      |
| `np.matmul()`             | Matrix multiplication      |
| `@`                       | Matrix multiplication      |
| `A.T`                     | Transpose                  |
| `np.linalg.det()`         | Determinant                |
| `np.linalg.inv()`         | Inverse                    |
| `np.linalg.matrix_rank()` | Rank                       |
| `np.trace()`              | Trace                      |
| `np.linalg.eig()`         | Eigenvalues & Eigenvectors |
| `np.linalg.solve()`       | Solve linear equations     |


## 📝 Summary

- Linear Algebra is essential for Machine Learning.
- NumPy provides the `numpy.linalg` module for matrix operations.
- Matrix multiplication, determinant, inverse, and eigenvalues are commonly used in ML algorithms.
- Understanding these concepts helps in PCA, Regression, Neural Networks, and Optimization.