# 🎲 NumPy Random Module

## 🎯 Learning Objectives

- Understand random number generation in NumPy.
- Generate random integers and floating-point numbers.
- Create normally distributed random values.
- Randomly select, shuffle, and permute data.
- Ensure reproducible results using random seeds.

## 📖 Introduction

The NumPy Random Module provides functions to generate random numbers for simulations, testing, data sampling, machine learning, and statistical analysis. Setting a random seed ensures reproducible results, which is essential for experiments and model evaluation.

In [1]:
import numpy as np

## 🔹 `np.random.seed()`

Initializes the random number generator to produce the same sequence of random numbers every time the program runs.

In [2]:
np.random.seed(42)

print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


## 🔹 `np.random.rand()`

Generates random floating-point numbers between **0 and 1**.

In [3]:
print(np.random.rand())

print(np.random.rand(5))

print(np.random.rand(2,3))

0.5986584841970366
[0.15601864 0.15599452 0.05808361 0.86617615 0.60111501]
[[0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]


## 🔹 `np.random.randn()`

Generates random numbers from the standard normal distribution (mean = 0, standard deviation = 1).

In [4]:
print(np.random.randn())

print(np.random.randn(4))

print(np.random.randn(2,3))

-0.5713801657541415
[-0.92408284 -2.61254901  0.95036968  0.81644508]
[[-1.523876   -0.42804606 -0.74240684]
 [-0.7033438  -2.13962066 -0.62947496]]


## 🔹 `np.random.randint()`

Generates random integers within a specified range.

**Syntax**

```python
np.random.randint(low, high, size)
```

In [5]:
print(np.random.randint(1,10))

print(np.random.randint(1,100,5))

print(np.random.randint(0,50,(2,3)))

7
[64  3 51  7 21]
[[ 8 38 17]
 [ 3 24 13]]


## 🔹 `np.random.choice()`

Randomly selects values from a given array or list.

In [6]:
colors = ["Red","Blue","Green","Yellow"]

print(np.random.choice(colors))

print(np.random.choice(colors,3))

Blue
['Blue' 'Red' 'Blue']


## 🔹 `np.random.shuffle()`

Randomly shuffles the elements of an array **in-place**.

In [7]:
arr = np.array([1,2,3,4,5])

np.random.shuffle(arr)

print(arr)

[1 4 3 2 5]


## 🔹 `np.random.permutation()`

Returns a shuffled copy of an array without modifying the original array.

In [8]:
arr = np.array([1,2,3,4,5])

print(np.random.permutation(arr))

print(arr)

[2 5 3 1 4]
[1 2 3 4 5]


## 🔹 Random Sampling

Randomly select multiple elements from an array.

In [9]:
numbers = np.arange(1,21)

sample = np.random.choice(numbers,5,replace=False)

print(sample)

[ 1  3 19 11  9]


## 🔹 Generate Random Matrix

In [10]:
matrix = np.random.randint(1,100,(3,3))

print(matrix)

[[62 14 95]
 [48 15 72]
 [78 87 62]]


| Function        | Purpose                     |
| --------------- | --------------------------- |
| `seed()`        | Reproducible random numbers |
| `rand()`        | Random floats (0–1)         |
| `randn()`       | Normal distribution         |
| `randint()`     | Random integers             |
| `choice()`      | Random selection            |
| `shuffle()`     | Shuffle original array      |
| `permutation()` | Shuffled copy               |
| Random Sampling | Select random samples       |


## 📝 Summary

- NumPy provides efficient functions for generating random numbers.
- `seed()` ensures reproducibility.
- `rand()` generates uniformly distributed values.
- `randn()` generates normally distributed values.
- `shuffle()` modifies the original array, while `permutation()` returns a new shuffled array.
- Random sampling is widely used in Machine Learning and Data Analysis.